### ISSUE TITLE
rpc-zigzag has a namespace colision with zigzag

### ISSUE THREAD

**Issue by prometheanfire** [rcbops/zigzag#23]

**Comment by ryan-rs** [comment]
@prometheanfire Can you give us some more context on where the collision is happening?

**Comment by zreichert** [comment]
@prometheanfire Did you want to use rpc-zigzag and jbn/zigzag in the same runtime?

**Comment by prometheanfire** [comment]
Nope, just calling out that you have a possible namespace collision (which would have been caught if this was uploaded to pypi).  I don't use either library.

**Comment by zreichert** [comment]
@prometheanfire This is uploaded to PyPI https://pypi.org/project/rpc-zigzag/ 

I will file a ticket on our internal Jira to track this issue.  I will add you as a watcher
